name: Publish to PyPI

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose your Python version

      - name: Install dependencies
        run: pip install -r requirements.txt  # If you have a requirements file

      - name: Build and publish to PyPI
        run: |
          python setup.py sdist
          pip install twine
          twine upload --skip-existing --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
